#!/bin/bash
docker run \
    -d --restart always \
    --name mysql8 \
    -p3306:3306 \
    -e MYSQL_ROOT_PASSWORD=password \
    -v ~/.mysql_data8:/var/lib/mysql \
    mysql:8 \
    --character-set-server=utf8mb4 \
    --collation-server=utf8mb4_unicode_ci
