#!/bin/bash
DENV_HOST=`hostname -I | awk '{ print $1 }'`
opt=""
for I; do
  opt+="-p ${I}:${I} "
done
podman run \
    -dt --name denv --restart always \
    --add-host="denv.host:$DENV_HOST" \
    -v $PWD:$PWD -w $PWD \
    -v ~/.devenviron/.gitconfig:/root/.gitconfig \
    -v ~/.devenviron/.git-credentials:/root/.git-credentials \
    -v ~/.devenviron/.awsconfig:/root/.aws/config \
    -v ~/.devenviron/.aws-credentials:/root/.aws/credentials \
    -v ~/.devenviron/.npmrc:/root/.npmrc \
    -v ~/.devenviron/.ssh:/root/.ssh \
    ${opt} \
    tamuto/devenviron:latest
