images:
  - location: "https://cloud-images.ubuntu.com/impish/current/impish-server-cloudimg-amd64.img"
    arch: "x86_64"
  - location: "https://cloud-images.ubuntu.com/impish/current/impish-server-cloudimg-arm64.img"
    arch: "aarch64"
mounts:
  - location: "~"
    writable: false
  - location: "/tmp/lima"
    writable: true
disk: "30GiB"
ssh:
  localPort: 60906
containerd:
  system: false
  user: false
provision:
  - mode: system
    script: |
      #!/bin/bash
      set -eux -o pipefail
      command -v podman >/dev/null 2>&1 && exit 0
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      apt-get install -y podman crun
  - mode: user
    script: |
      #!/bin/bash
      mkdir -p ~/.config/containers
      cat <<EOF > ~/.config/containers/containers.conf
      [engine]
      event_logger = "file"
      cgroup_manager = "cgroupfs"
      EOF
      cat <<EOF > ~/.config/containers/registries.conf
      [registries.search]
      registries = ['docker.io']

      [registries.insecure]
      registries = []

      [registries.block]
      registries = []
      EOF
      mkdir -p ~/bin
      cat <<EOF > ~/bin/denvcp
      cp /Users/$USER/.devenviron/.* ~/.devenviron
      EOF
      chmod +x ~/bin/denvcp

