if [ -e /etc/bash_completion.d/git-prompt ]; then
    source /etc/bash_completion.d/git-prompt
    PS1='\[\e]0;\w\a\]${debian_chroot:+($debian_chroot)}\[\[\033[01;34m\]\w\[\033[00m\]$(__git_ps1 " (%s)") \n\$ '
fi
source /usr/share/bash-completion/completions/git
set -o noclobber

alias ncu='bunx npm-check-updates'
