FROM {{BASEIMG}}

RUN apt-get update && apt-get install -y \
    curl build-essential git sqlite3 \
    software-properties-common gnupg sudo iputils-ping net-tools ftp p7zip-full \
    default-mysql-client php subversion ffmpeg sox {{CHROMIUM}} fonts-ipafont fonts-ipaexfont \
    openjdk-17-jdk-headless maven
RUN curl -L https://deb.nodesource.com/setup_lts.x | bash - \
&&  apt-get install -y nodejs \
&&  curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add - \
&&  apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main" \
&&  apt-get update && apt-get install terraform \
&&  apt-get clean && rm -rf /var/lib/apt/lists/* \
&&  curl "https://awscli.amazonaws.com/awscli-exe-linux-{{ARCH}}.zip" -o "awscliv2.zip" \
&&  7z x awscliv2.zip \
&&  ./aws/install \
&&  rm -rf ./aws \
&&  rm awscliv2.zip

COPY --from=composer /usr/bin/composer /usr/bin/composer
# RUN pip install --upgrade pip
RUN pip install \
    poetry \
    boto \
    boto3 \
    twine \
    setuptools_scm \
    python-dotenv[cli]

RUN npm install -g @infodb/infodb-cli@0.11.2 npm-check-updates pnpm \
&&  poetry config virtualenvs.in-project true \
&&  curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/{{SSM_ARCH}}/session-manager-plugin.deb" -o "session-manager-plugin.deb" \
&&  dpkg -i session-manager-plugin.deb \
&&  rm session-manager-plugin.deb

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y \
&&  /root/.cargo/bin/cargo install wasm-pack

COPY resources/bash_aliases /root/.bashrc
COPY resources/ssh-aws.sh /usr/local/bin/ssh-aws.sh

ENTRYPOINT [""]
CMD ["/bin/bash"]
